### ISSUE TITLE
Interface 'Pimple\ServiceProviderInterface' not found 

### ISSUE THREAD

**Issue by dotzero** [KuiKui/MemcacheServiceProvider#16]
Hi,
I have some error:

PHP Fatal error:  Interface Pimple\ServiceProviderInterface not found in `/vendor/kuikui/memcache-service-provider/src/KuiKui/MemcacheServiceProvider/ServiceProvider.php` on line 23

Maybe `use Pimple\ServiceProviderInterface;` 
must be replaced with `use Silex\ServiceProviderInterface;`

**Comment by KuiKui** [comment]
Which version of Silex do you use ?
Cause this error can occur if you use MemcacheServiceProvider `2.*` with Silex `1.*`.

**Comment by dotzero** [comment]
My bad, i'm using silex v1.3.0
