### ISSUE TITLE
Fatal error in ServiceProvider

### ISSUE THREAD

**Issue by northern** [KuiKui/MemcacheServiceProvider#6]
Hi,

I have a server on PHP 5.3.10-1ubuntu3.8 with the following Memcached version:

    memcached support enabled
    Version 1.0.2
    libmemcached version 0.44
    Session support yes
    igbinary support no

I agree, it's a little bit outdated but would there be a specific reason why the following error might be thrown:

    PHP Fatal error:  Using $this when not in object context in vendor/kuikui/memcache-service-provider/src/KuiKui/MemcacheServiceProvider/ServiceProvider.php on line 26

Thanks,
Luke

**Comment by KuiKui** [comment]
Fixed by #12
